spring:
  profiles:
    active: dev

app:
  jwt:
    signing-key: somestrongkey
    claim-name: scopes
    expiration: 86400000
    token-prefix: Bearer
  api-fetch:
    initial-delay: 10000
    fixed-delay: 600000

currency-exchange:
  exchange-rate:
    api-key: a748d31bfa244a793bec79fb
    base-url: https://v6.exchangerate-api.com/v6
    path: /${currency-exchange.exchange-rate.api-key}/latest/{currency}
  rates:
    base-url: https://api.ratesapi.io/api
    path: /latest?base={currency}

springdoc:
  swagger-ui:
    path: /docs/swagger-ui
  api-docs:
    path: /docs/api-docs
  paths-to-match: /api/v1/**
